version: '3.0'
services:

  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mymssql
    ports:
      - 1435:1433
    volumes:
      - /var/opt/mssql
    # we copy our scripts onto the container
      - ./:/usr/src/app
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app
    # run the entrypoint.sh that will create tables in sqlserver
    # command: sh -c ' chmod +x /usr/src/app/entrypoint.sh;'
    command: sh -c ' /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P HappyNew@123 -d master -i setup.sql && wait'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: HappyNew@123
    networks: 
      - backend
  tomcat:
    image: tomcat:8.0-alpine
    container_name: mytomcat
    volumes:
      - ./target/PaymentBilling.war:/usr/local/tomcat/webapps/PaymentBilling.war
    # - ./jarfiles:/usr/local/tomcat/lib
    ports:
      - "9090:8080"
    depends_on:
      - mssql
    links:
      - mssql
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"