# Pull base image
FROM tomcat:8.0-alpine
# Maintainer
LABEL MAINTAINER "sharath.bannanje@gmail.com">
# Best Practice
EXPOSE 8080
# Cmd to clear the web folder
RUN rm -rf /usr/local/tomcat/webapps/*
COPY ./target/PaymentBilling.war /usr/local/tomcat/webapps/PaymentBilling.war
CMD ["catalina.sh", "run"]